language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"
    # Test against LTS versions of Symfony
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
  allow_failures:
    - php: hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist $COMPOSER_FLAGS

script:
  - ./vendor/bin/phpunit
